---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: polkadot-polkadot-data
  namespace: polkadot
spec:
  resources:
    requests:
      storage: 200Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
