---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: telemetry
spec:
  replicas: 2
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: telemetry
  template:
    metadata:
      labels:
        app: telemetry
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - telemetry
              topologyKey: "kubernetes.io/hostname"
      containers:
        - name: core
          image: parity/substrate-telemetry-backend
          command:
            - telemetry_core
            - -l
            - 0.0.0.0:8888
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
            requests:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 8888
          securityContext:
            runAsUser: 1000
            readOnlyRootFilesystem: true
          livenessProbe:
            httpGet:
              path: /health
              port: http
          readinessProbe:
            httpGet:
              path: /health
              port: http
        - name: frontend
          image: parity/substrate-telemetry-frontend
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
            requests:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 8000
          env:
            - name: SUBSTRATE_TELEMETRY_URL
              valueFrom:
                configMapKeyRef:
                  name: config-telemetry
                  key: substrate_telemetry_url
          securityContext:
            runAsUser: 101
            readOnlyRootFilesystem: true
          volumeMounts:
            - mountPath: /var/cache/nginx
              name: nginx-cache
            - mountPath: /var/run
              name: run
            - mountPath: /app/tmp
              name: tmp
      volumes:
        - name: nginx-cache
          emptyDir: {}
        - name: run
          emptyDir: {}
        - name: tmp
          emptyDir: {}
