---
apiVersion: v1
kind: Service
metadata:
  name: telemetry-frontend
spec:
  type: LoadBalancer
  selector:
    app: telemetry
  ports:
    - port: 8000
      targetPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: telemetry-core
  annotations:
    cloud.google.com/backend-config: '{"ports": {"8888":"telemetry-core-backendconfig"}}'
    cloud.google.com/neg: '{"ingress": true}'
spec:
  type: LoadBalancer
  selector:
    app: telemetry
  ports:
    - port: 8888
      targetPort: 8888
---
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: telemetry-core-backendconfig
spec:
  timeoutSec: 120
  healthCheck:
    checkIntervalSec: 15
    timeoutSec: 15
    healthyThreshold: 1
    unhealthyThreshold: 2
    type: HTTP
    requestPath: "/health"