---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: polkadot-polkadot
  namespace: polkadot
spec:
  selector:
    matchLabels:
      app: polkadot-polkadot
  template:
    metadata:
      labels:
        app: polkadot-polkadot
    spec:
      initContainers:
        - name: chown
          image: busybox
          command:
            - chown
            - -R
            - "1000:1000"
            - /polkadot
          volumeMounts:
            - mountPath: /polkadot
              name: polkadot-polkadot-data
      containers:
        - name: polkadot-polkadot
          image: parity/polkadot:v0.9.17
          securityContext:
            readOnlyRootFilesystem: true
            runAsUser: 1000
          command:
            - polkadot
            - --validator
            - --name=EQDot
            - --telemetry-url
            - "ws://localhost:8001/submit 0"
          resources:
            requests:
              memory: 7500Mi
              cpu: 2500m
            limits:
              memory: 7500Mi
              cpu: 2500m
          ports:
            - containerPort: 30333
            - containerPort: 9944
          volumeMounts:
            - mountPath: /polkadot
              name: polkadot-polkadot-data
            - mountPath: /tmp
              name: tmp
        - name: sharding
          image: parity/substrate-telemetry-backend
          command:
            - telemetry_shard
            - -l
            - 0.0.0.0:8001
            - -c
            - http://telemetry-core:8888/shard_submit
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
            requests:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 8001
          securityContext:
            runAsUser: 1000
            readOnlyRootFilesystem: true
      volumes:
        - name: polkadot-polkadot-data
          persistentVolumeClaim:
            claimName: polkadot-polkadot-data
        - name: tmp
          emptyDir: {}
